import { type } from "arktype";

export const env = type({
  API_PORT: "string",
  ANTHROPIC_API_KEY: "string?",
  CLAUDE_CODE_OAUTH_CREDENTIALS: "string?",
  BROWSER_API_URL: "string",
  BROWSER_WS_URL: "string",
  CONTAINER_SCHEME: "string",
  PROXY_INTERNAL_URL: "string",
  BROWSER_CLEANUP_DELAY_MS: "string.integer.parse = '10000'",
  RECONCILE_INTERVAL_MS: "string.integer.parse = '5000'",
  MAX_DAEMON_RETRIES: "string.integer.parse = '3'",
  BROWSER_SOCKET_VOLUME: "string = 'lab_browser_sockets'",
  BROWSER_CONTAINER_NAME: "string",
  PROXY_CONTAINER_NAME: "string",
  PROXY_BASE_URL: "string",
  POOL_SIZE: "string.integer.parse = '0'",
  GITHUB_CLIENT_ID: "string?",
  GITHUB_CLIENT_SECRET: "string?",
  GITHUB_CALLBACK_URL: "string?",
  FRONTEND_URL: "string?",
  BETTER_AUTH_SECRET: "string",
  BETTER_AUTH_URL: "string",
  AUTH_GITHUB_CLIENT_ID: "string",
  AUTH_GITHUB_CLIENT_SECRET: "string",
  REDIS_URL: "string = 'redis://localhost:6379'",
  SANDBOX_AGENT_URL: "string = 'http://lab-acp-proxy:3000'",
  SANDBOX_AGENT_MCP_URL: "string?",
});
